env: "utracking"

env_args:
  key: utracking # just for saving
  map_name: "5v5"
  time_limit: 400 # how many timesteps to run
  pretrained_wrapper: null # not sure about this
  scenario_name: tracking
  num_agents: 5
  num_landmarks: 5
  landmark_depth: 15.
  landmark_movable: True
  agent_vel: 0.3
  landmark_vel: 0.05
  max_vel: 0.2
  random_vel: False
  sense_range: 0.5 #how far the agent can see the position and slants of other agents
  max_range: 1. # how far the agent can make a measurement in respect to the landmark
  max_current_vel: 0.
  movement: turning # levy, linear or turning
  pf_method: False
  rew_err_th: 0.05
  rew_dis_th: 0.3
  benchmark: True
  only_closer_agent_pos: True
  use_custom_state: False
  min_init_dist: 0.2 # minimum distance between agents and between agents and landmarks at episode start
  max_init_dist: 0.5 # maximum distance of the closest agent at the beginning of episode 
  difficulty: control
  obs_entity_mode: False # for transformers


use_cuda: True
use_rnn: True

standardise_returns: False
standardise_rewards: False

checkpoint_path: ""


#test config
evaluate: True
runner: "episode"
batch_size_run: 1
batch_size: 1
manual_seed: False

#logs s
save_animation: False 
use_tensorboard: False
save_model: False
local_results_path: "results_curr_5v5"
test_greedy: True
test_nepisode: 100
test_interval: 40000
log_interval: 40000
animation_interval: 20000
animation_interval_evaluation: 200
runner_log_interval: 20000
learner_log_interval: 20000
t_max: 100050000